name: BuildWithDeploy
on: [push]
jobs:
  buildwithdeploy:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v3
       - uses: actions/setup-node@v3
         with: 
            node-version: '14'
       - run: yarn install
       - name: Run build task
         run: yarn docs:build
       - name: Deploy to Server
         uses: easingthemes/ssh-deploy@main
         env:
              SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
              ARGS: "-rltgoDzvO --delete"
              SOURCE: "docs/.vuepress/dist/"
              REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
              REMOTE_USER: ${{ secrets.REMOTE_USER }}
              TARGET: ${{ secrets.REMOTE_TARGET }}
              # EXCLUDE: "/dist/, /node_modules/"
